# Generated by Django 4.2.6 on 2023-10-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_tag_rename_content_post_body_post_author_post_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog.tag"),
        ),
    ]
