# Generated by Django 4.2.6 on 2023-10-31 01:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0006_recomment_author_alter_recomment_comment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReComment",
            new_name="ReplyComment",
        ),
    ]
