# Generated by Django 4.2.6 on 2023-10-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/blog/%Y/%m/%d/",
                verbose_name="썸네일",
            ),
        ),
    ]
