# Generated by Django 4.2.6 on 2023-10-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                help_text="닉네임은 고유합니다!", max_length=50, unique=True, verbose_name="닉네임"
            ),
        ),
    ]
